"""C Transpiler / Native Code Generator for Fresh.

Transforms a Fresh AST into standalone, readable C source code for native compilation
with GCC, Clang, or MSVC.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from fresh.analyzer.resolver import Resolver
from fresh.analyzer.type_checker import TypeChecker, TypedProgram
from fresh.codegen.capabilities import validate_ast_for_backend
from fresh.common.errors import FreshCodegenError
from fresh.common.types import FreshBool, FreshFloat, FreshInt, FreshString, FreshStruct
from fresh.parser.ast import (
    AssignExpr,
    BinaryExpr,
    BlockStmt,
    BreakStmt,
    CallExpr,
    ContinueStmt,
    Expr,
    ExprStmt,
    FieldAccessExpr,
    FieldSetExpr,
    FnDeclStmt,
    ForStmt,
    IfStmt,
    ImportStmt,
    IndexExpr,
    IndexSetExpr,
    LambdaExpr,
    LiteralExpr,
    LogicalExpr,
    MatchExpr,
    ReturnStmt,
    Stmt,
    StructDeclStmt,
    StructLiteralExpr,
    UnaryExpr,
    VarDeclStmt,
    VariableExpr,
    WhileStmt,
)

if TYPE_CHECKING:
    from fresh.parser.ast import TypeAnnotation


C_RESERVED_WORDS = {
    "auto", "char", "const", "default", "do",
    "double", "enum", "extern", "float", "goto",
    "inline", "int", "long", "register", "restrict", "short",
    "signed", "sizeof", "static", "switch", "typedef", "union",
    "unsigned", "void", "volatile", "_Alignas", "_Alignof",
    "_Atomic", "_Bool", "_Complex", "_Generic", "_Imaginary", "_Noreturn",
    "_Static_assert", "_Thread_local"
}


def mangle_c_ident(name: str) -> str:
    """Sanitize Fresh identifiers that clash with C99 reserved keywords."""
    if name in C_RESERVED_WORDS:
        return f"f_{name}"
    return name


class CTranspiler:
    """Translates Fresh AST to clean, executable C source code."""

    def __init__(self, filename: str = "<stdin>") -> None:
        self.filename = filename
        self.var_types: dict[str, str] = {}
        self.fn_ret_types: dict[str, str] = {}
        self.struct_defs: dict[str, dict[str, str]] = {}
        self.typed_prog: TypedProgram | None = None

    def transpile(self, statements: list[Stmt] | TypedProgram) -> str:
        """Transpile Fresh AST / TypedProgram into C code using canonical semantic types."""
        if isinstance(statements, TypedProgram):
            self.typed_prog = statements
            main_statements = self.typed_prog.statements
        else:
            main_statements = statements
            validate_ast_for_backend(main_statements, backend="native_c", filename=self.filename)
            try:
                Resolver(filename=self.filename).resolve_program(main_statements)
                self.typed_prog = TypeChecker(filename=self.filename).check_program(main_statements)
            except Exception:
                self.typed_prog = None

        validate_ast_for_backend(main_statements, backend="native_c", filename=self.filename)

        self.var_types.clear()
        self.fn_ret_types.clear()
        self.struct_defs.clear()

        c_code: list[str] = [
            "// Generated by Fresh Compiler C Transpiler",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <stdbool.h>",
            "#include <string.h>",
            "#include <time.h>",
            "",
            "// Helper runtimes",
            "void println_int(long long v) { printf(\"%lld\\n\", v); }",
            "void println_float(double v) {",
            "    char buf[64];",
            "    snprintf(buf, sizeof(buf), \"%g\", v);",
            "    if (!strchr(buf, '.') && !strchr(buf, 'e') && !strchr(buf, 'E')) {",
            "        strcat(buf, \".0\");",
            "    }",
            "    printf(\"%s\\n\", buf);",
            "}",
            "void println_str(const char* v) { printf(\"%s\\n\", v); }",
            "void println_bool(bool v) { printf(\"%s\\n\", v ? \"true\" : \"false\"); }",
            "double clock_sec() { return (double)clock() / CLOCKS_PER_SEC; }",
            "",
            "static inline long long fresh_div_int(long long a, long long b) {",
            "    if (b == 0) {",
            "        fprintf(stderr, \"error[FreshRuntimeError]: Division by zero [E5001]\\n\");",
            "        exit(1);",
            "    }",
            "    return a / b;",
            "}",
            "static inline long long fresh_mod_int(long long a, long long b) {",
            "    if (b == 0) {",
            "        fprintf(stderr, \"error[FreshRuntimeError]: Modulo by zero [E5001]\\n\");",
            "        exit(1);",
            "    }",
            "    return a % b;",
            "}",
            "static inline double fresh_div_float(double a, double b) {",
            "    if (b == 0.0) {",
            "        fprintf(stderr, \"error[FreshRuntimeError]: Division by zero [E5001]\\n\");",
            "        exit(1);",
            "    }",
            "    return a / b;",
            "}",
            "static inline const char* fresh_str_concat(const char* a, const char* b) {",
            "    size_t len_a = strlen(a);",
            "    size_t len_b = strlen(b);",
            "    char* buf = (char*)malloc(len_a + len_b + 1);",
            "    if (!buf) {",
            "        fprintf(stderr, \"error[FreshRuntimeError]: Out of memory\\n\");",
            "        exit(1);",
            "    }",
            "    strcpy(buf, a);",
            "    strcat(buf, b);",
            "    return buf;",
            "}",
            "static inline const char* fresh_to_string_int(long long v) {",
            "    char* buf = (char*)malloc(32);",
            "    if (!buf) { fprintf(stderr, \"error[FreshRuntimeError]: Out of memory\\n\"); exit(1); }",
            "    snprintf(buf, 32, \"%lld\", v);",
            "    return buf;",
            "}",
            "static inline const char* fresh_to_string_float(double v) {",
            "    char* buf = (char*)malloc(64);",
            "    if (!buf) { fprintf(stderr, \"error[FreshRuntimeError]: Out of memory\\n\"); exit(1); }",
            "    snprintf(buf, 64, \"%g\", v);",
            "    if (!strchr(buf, '.') && !strchr(buf, 'e') && !strchr(buf, 'E')) { strcat(buf, \".0\"); }",
            "    return buf;",
            "}",
            "static inline const char* fresh_to_string_bool(bool v) {",
            "    return v ? \"true\" : \"false\";",
            "}",
            "static inline const char* fresh_to_string_str(const char* v) {",
            "    return v;",
            "}",
            "static inline double fresh_clock() {",
            "    return (double)clock() / (double)CLOCKS_PER_SEC;",
            "}",
            "",
        ]

        main_stmts: list[Stmt] = []

        for stmt in main_statements:
            if isinstance(stmt, (FnDeclStmt, StructDeclStmt)):
                c_code.append(self._transpile_stmt(stmt, indent=0))
                c_code.append("")
            else:
                main_stmts.append(stmt)

        c_code.append("int main() {")
        for stmt in main_stmts:
            c_code.append(self._transpile_stmt(stmt, indent=1))
        c_code.append("    return 0;")
        c_code.append("}")

        return "\n".join(c_code)

    def _transpile_stmt(self, stmt: Stmt, indent: int) -> str:
        pad = "    " * indent

        match stmt:
            case VarDeclStmt(name=name, type_annotation=ta, initializer=init):
                c_type = self._transpile_type(ta) if ta else None
                inferred_fresh_type = self._infer_expr_type(init)

                if c_type is None:
                    if inferred_fresh_type == "float":
                        c_type = "double"
                    elif inferred_fresh_type == "string":
                        c_type = "const char*"
                    elif inferred_fresh_type == "bool":
                        c_type = "bool"
                    elif inferred_fresh_type == "int":
                        c_type = "long long"
                    elif inferred_fresh_type != "unknown":
                        c_type = inferred_fresh_type
                    else:
                        c_type = "long long"

                self.var_types[name.lexeme] = self._c_type_to_fresh_type(c_type)
                return f"{pad}{c_type} {mangle_c_ident(name.lexeme)} = {self._transpile_expr(init)};"

            case FnDeclStmt(name=name, params=params, return_type=rt, body=body):
                ret_type = self._transpile_type(rt) if rt else "void"
                c_fn_name = "fresh_main" if name.lexeme == "main" else mangle_c_ident(name.lexeme)
                self.fn_ret_types[name.lexeme] = self._c_type_to_fresh_type(ret_type)
                param_strs = [
                    f"{self._transpile_type(p.type_annotation)} {mangle_c_ident(p.name.lexeme)}"
                    for p in params
                ]
                for p in params:
                    if p.type_annotation:
                        self.var_types[p.name.lexeme] = p.type_annotation.name.lexeme

                body_lines = [self._transpile_stmt(s, indent=1) for s in body]
                return f"{pad}{ret_type} {c_fn_name}({', '.join(param_strs)}) {{\n" + "\n".join(body_lines) + f"\n{pad}}}"

            case StructDeclStmt(name=name, fields=fields):
                field_dict = {}
                field_decls = []
                for f in fields:
                    ftype = self._transpile_type(f.type_annotation)
                    field_dict[f.name.lexeme] = self._c_type_to_fresh_type(ftype)
                    field_decls.append(f"    {ftype} {f.name.lexeme};")
                self.struct_defs[name.lexeme] = field_dict
                return f"{pad}typedef struct {name.lexeme} {{\n" + "\n".join(field_decls) + f"\n{pad}}} {name.lexeme};"

            case IfStmt(condition=cond, then_branch=then_b, else_branch=else_b):
                cond_str = self._transpile_expr(cond)
                then_lines = [self._transpile_stmt(s, indent=indent + 1) for s in then_b]
                res = f"{pad}if ({cond_str}) {{\n" + "\n".join(then_lines) + f"\n{pad}}}"
                if else_b:
                    else_lines = [self._transpile_stmt(s, indent=indent + 1) for s in else_b]
                    res += " else {\n" + "\n".join(else_lines) + f"\n{pad}}}"
                return res

            case WhileStmt(condition=cond, body=body):
                cond_str = self._transpile_expr(cond)
                body_lines = [self._transpile_stmt(s, indent=indent + 1) for s in body]
                return f"{pad}while ({cond_str}) {{\n" + "\n".join(body_lines) + f"\n{pad}}}"

            case ForStmt(initializer=init, condition=cond, increment=inc, body=body):
                init_str = self._transpile_stmt(init, indent=0).strip().rstrip(";") if init else ""
                cond_str = self._transpile_expr(cond) if cond else "1"
                inc_str = self._transpile_expr(inc) if inc else ""
                body_lines = [self._transpile_stmt(s, indent=indent + 1) for s in body]
                return f"{pad}for ({init_str}; {cond_str}; {inc_str}) {{\n" + "\n".join(body_lines) + f"\n{pad}}}"

            case ReturnStmt(value=val):
                if val:
                    return f"{pad}return {self._transpile_expr(val)};"
                return f"{pad}return;"

            case BreakStmt():
                return f"{pad}break;"

            case ContinueStmt():
                return f"{pad}continue;"

            case ExprStmt(expression=expr):
                return f"{pad}{self._transpile_expr(expr)};"

            case BlockStmt(statements=stmts):
                lines = [self._transpile_stmt(s, indent=indent + 1) for s in stmts]
                return f"{pad}{{\n" + "\n".join(lines) + f"\n{pad}}}"

            case ImportStmt():
                return ""

            case _:
                raise FreshCodegenError(
                    message=f"[E3001] C backend does not support statement '{type(stmt).__name__}'.",
                    line=getattr(stmt, "line", 0),
                    filename=self.filename,
                )

    def _transpile_expr(self, expr: Expr) -> str:
        match expr:
            case LiteralExpr(value=val):
                if val is True:
                    return "true"
                if val is False:
                    return "false"
                if val is None:
                    return "NULL"
                if isinstance(val, str):
                    return f'"{val}"'
                return str(val)

            case VariableExpr(name=name):
                return mangle_c_ident(name.lexeme)

            case AssignExpr(name=name, value=val):
                return f"({mangle_c_ident(name.lexeme)} = {self._transpile_expr(val)})"

            case BinaryExpr(left=l, operator=op, right=r):
                l_str = self._transpile_expr(l)
                r_str = self._transpile_expr(r)
                l_type = self._infer_expr_type(l)
                r_type = self._infer_expr_type(r)

                if op.lexeme == "/":
                    if l_type == "float" or r_type == "float":
                        return f"fresh_div_float({l_str}, {r_str})"
                    return f"fresh_div_int({l_str}, {r_str})"

                if op.lexeme == "%":
                    return f"fresh_mod_int({l_str}, {r_str})"

                if op.lexeme == "+" and (l_type == "string" or r_type == "string"):
                    return f"fresh_str_concat({l_str}, {r_str})"

                return f"({l_str} {op.lexeme} {r_str})"

            case LogicalExpr(left=l, operator=op, right=r):
                return f"({self._transpile_expr(l)} {op.lexeme} {self._transpile_expr(r)})"

            case UnaryExpr(operator=op, operand=operand):
                return f"({op.lexeme}{self._transpile_expr(operand)})"

            case CallExpr(callee=callee, arguments=args):
                callee_str = self._transpile_expr(callee)

                if callee_str == "println":
                    if args:
                        first_arg_str = self._transpile_expr(args[0])
                        arg_type = self._infer_expr_type(args[0])
                        if arg_type == "float":
                            return f"println_float({first_arg_str})"
                        elif arg_type == "string":
                            return f"println_str({first_arg_str})"
                        elif arg_type == "bool":
                            return f"println_bool({first_arg_str})"
                        else:
                            return f"println_int({first_arg_str})"
                    return 'printf("\\n")'

                if callee_str == "to_string":
                    if args:
                        first_arg_str = self._transpile_expr(args[0])
                        arg_type = self._infer_expr_type(args[0])
                        if arg_type == "float":
                            return f"fresh_to_string_float({first_arg_str})"
                        elif arg_type == "bool":
                            return f"fresh_to_string_bool({first_arg_str})"
                        elif arg_type == "string":
                            return f"fresh_to_string_str({first_arg_str})"
                        else:
                            return f"fresh_to_string_int({first_arg_str})"
                    return '""'

                if callee_str == "clock":
                    return "fresh_clock()"

                if callee_str == "main":
                    callee_str = "fresh_main"

                args_str = ", ".join(self._transpile_expr(a) for a in args)
                return f"{callee_str}({args_str})"

            case IndexExpr(obj=obj, index=idx):
                return f"{self._transpile_expr(obj)}[{self._transpile_expr(idx)}]"

            case IndexSetExpr(obj=obj, index=idx, value=val):
                return f"({self._transpile_expr(obj)}[{self._transpile_expr(idx)}] = {self._transpile_expr(val)})"

            case FieldAccessExpr(obj=obj, name=name):
                return f"{self._transpile_expr(obj)}.{name.lexeme}"

            case FieldSetExpr(obj=obj, name=name, value=val):
                return f"({self._transpile_expr(obj)}.{name.lexeme} = {self._transpile_expr(val)})"

            case StructLiteralExpr(name=name, fields=fields):
                field_inits = ", ".join(
                    f".{f[0].lexeme} = {self._transpile_expr(f[1])}" for f in fields
                )
                return f"({name.lexeme}){{ {field_inits} }}"

            case MatchExpr() | LambdaExpr():
                raise FreshCodegenError(
                    message=f"[E3001] C backend does not support '{type(expr).__name__}'.",
                    line=getattr(expr, "line", 0),
                    filename=self.filename,
                )

            case _:
                raise FreshCodegenError(
                    message=f"[E3001] C backend does not support expression '{type(expr).__name__}'.",
                    line=getattr(expr, "line", 0),
                    filename=self.filename,
                )

    def _infer_expr_type(self, expr: Expr) -> str:
        if self.typed_prog is not None:
            t = self.typed_prog.get_type(expr)
            if isinstance(t, FreshInt):
                return "int"
            if isinstance(t, FreshFloat):
                return "float"
            if isinstance(t, FreshBool):
                return "bool"
            if isinstance(t, FreshString):
                return "string"
            if isinstance(t, FreshStruct):
                return t.name

        match expr:
            case LiteralExpr(value=val):
                if isinstance(val, bool):
                    return "bool"
                if isinstance(val, float):
                    return "float"
                if isinstance(val, int):
                    return "int"
                if isinstance(val, str):
                    return "string"
                return "unknown"

            case VariableExpr(name=name):
                return self.var_types.get(name.lexeme, "unknown")

            case AssignExpr(value=val):
                return self._infer_expr_type(val)

            case BinaryExpr(left=l, operator=op, right=r):
                if op.lexeme in ("==", "!=", "<", "<=", ">", ">="):
                    return "bool"
                l_t = self._infer_expr_type(l)
                r_t = self._infer_expr_type(r)
                if op.lexeme == "+" and (l_t == "string" or r_t == "string"):
                    return "string"
                if l_t == "float" or r_t == "float":
                    return "float"
                return "int"

            case LogicalExpr():
                return "bool"

            case UnaryExpr(operator=op, operand=operand):
                if op.lexeme == "!":
                    return "bool"
                return self._infer_expr_type(operand)

            case CallExpr(callee=callee):
                callee_str = self._transpile_expr(callee)
                if callee_str == "to_string":
                    return "string"
                if callee_str == "clock":
                    return "int"
                return self.fn_ret_types.get(callee_str, "unknown")

            case StructLiteralExpr(name=name):
                return name.lexeme

            case FieldAccessExpr(obj=obj, name=name):
                obj_type = self._infer_expr_type(obj)
                if obj_type in self.struct_defs:
                    return self.struct_defs[obj_type].get(name.lexeme, "unknown")
                return "unknown"

            case _:
                return "unknown"

    def _transpile_type(self, ta: TypeAnnotation | None) -> str:
        if ta is None:
            return "void"
        tname = ta.name.lexeme
        match tname:
            case "int":
                return "long long"
            case "float":
                return "double"
            case "bool":
                return "bool"
            case "string":
                return "const char*"
            case _:
                return tname

    def _c_type_to_fresh_type(self, c_type: str) -> str:
        match c_type:
            case "long long":
                return "int"
            case "double":
                return "float"
            case "bool":
                return "bool"
            case "const char*":
                return "string"
            case _:
                return c_type
